// USER TYPES
export const SET_CURRENT_USER = 'user/SET_CURRENT_USER';

// CART TYPES
export const TOGGLE_CART_HIDDEN = 'cart/TOGGLE_CART_HIDDEN';
export const ADD_ITEM = 'cart/ADD_ITEM';
export const CLEAR_ITEM_FROM_CART = 'cart/CLEAR_ITEM_FROM_CART';
export const REMOVE_ITEM = 'cart/REMOVE_ITEM';

// SHOP TYPES
export const UPDATE_COLLECTIONS = 'shop/SHOP_COLLECTIONS';
export const FETCH_COLLECTIONS_START = 'shop/FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'shop/FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'shop/FETCH_COLLECTIONS_FAILURE';
